-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbLt3SoHZJBuDiWRj
NIrgN9ZfFyKo7XUy88Kjvoc/dPKgCgYIKoZIzj0DAQehRANCAAQ8JVSoCJ2z/A04
ZUVfxRUjHKTz3L6SaBxinskkTs5WnS8ndyWkE9wOy6v7fDRTxKMzR6goyQ/W8Q/X
BtkZ8TuX
-----END PRIVATE KEY-----